=head1 NAME

notmuch-extract-patch - extract a git patch series from notmuch

=head1 SYNOPSIS

B<notmuch-extract-patch> I<QUERY>

=head1 DESCRIPTION

B<notmuch-extract-patch> extracts a series of git patches from your
notmuch database.  It is designed to extract patches that were
originally sent using git-send-email(1).  It skips cover letters and
replies/reviews.

=head1 OPTIONS

None.

=head1 EXAMPLE

=over 4

    % git checkout -b test-feature
    % notmuch-extract-patch thread:000000000000265f | git am

=back

=head1 LIMITATIONS

B<notmuch-extract-patch> assumes one patch series per query.  So if
there is more than one patch series in a thread, you will need to
construct a notmuch query that includes only the patches you want to
extract, which somewhat defeats the purpose of this script.

This should not happen often because best practices when sharing
patches with git-send-email(1) include starting a new thread when
posting a revised series.  The I<--in-reply-to> option to
B<notmuch-extract-patch> is used mainly for posting a patch series in
reply to a bug report.

=head1 SEE ALSO

notmuch(1), git-send-email(1)

=head1 AUTHOR

B<notmuch-extract-patch> was written by Aurelien Aptel.  This manpage
was written by Sean Whitton <spwhitton@spwhitton.name> for the Debian
system, but may be used by others.
