=head1 NAME

notmuch-extract-patch - extract a git patch series from notmuch

=head1 SYNOPSIS

B<notmuch-extract-patch> [I<mbox-extract-patch(1) options>] [I<-->] I<QUERY>

=head1 DESCRIPTION

B<notmuch-extract-patch> is a wrapper around mbox-extract-patch(1) to
extract a series of git patches from your notmuch database.  It is
designed to extract patches that were originally sent using
git-send-email(1).  It skips cover letters and replies/reviews in its
output.

=head1 EXAMPLE

=over 4

    % git checkout -b test-feature
    % notmuch-extract-patch thread:000000000000265f | git am

=back

=head1 LIMITATIONS

We inherit limitations of mbox-extract-patch(1).

B<notmuch-extract-patch> can select patches to extract based on the
reroll count (see -v in mbox-extract-patch(1)), but otherwise typical
usage assumes that there is only one patch series in a thread.

If this assumption is violated, you would need to construct a notmuch
query that includes only the patches you want to extract, which
somewhat defeats the purpose of having this script.

=head1 SEE ALSO

notmuch(1), git-send-email(1), mbox-extract-patch(1)

Emacs functions 'notmuch-extract-thread-patches' and
'notmuch-extract-message-patches', provided by mailscripts.el

=head1 AUTHOR

Sean Whitton <spwhitton@spwhitton.name>

Rewrite, with additional features, of a script by Aurelien Aptel.
